CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE TABLE media (
        id uuid NOT NULL,
        path character varying(500) NOT NULL,
        title character varying(200) NOT NULL,
        original_title character varying(200) NOT NULL,
        description character varying(2000) NOT NULL,
        mime character varying(100) NOT NULL,
        size bigint,
        width integer,
        height integer,
        duration double precision,
        md5 character varying(32) NOT NULL,
        rating double precision,
        user_star_rating integer,
        published character varying(100) NOT NULL,
        ctime_ms bigint NOT NULL,
        mtime_ms bigint NOT NULL,
        created_on timestamp with time zone,
        updated_on timestamp with time zone,
        ffprobe JSONB NOT NULL,
        CONSTRAINT "PK_media" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE TABLE users (
        id uuid NOT NULL,
        user_name character varying(50) NOT NULL,
        password_hash character varying(50) NOT NULL,
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE TABLE media_cast (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        media_id uuid NOT NULL,
        cast_member character varying(50) NOT NULL,
        CONSTRAINT "PK_media_cast" PRIMARY KEY (id),
        CONSTRAINT "FK_media_cast_media_media_id" FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE TABLE media_directors (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        media_id uuid NOT NULL,
        director character varying(50) NOT NULL,
        CONSTRAINT "PK_media_directors" PRIMARY KEY (id),
        CONSTRAINT "FK_media_directors_media_media_id" FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE TABLE media_genres (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        media_id uuid NOT NULL,
        genre character varying(50) NOT NULL,
        CONSTRAINT "PK_media_genres" PRIMARY KEY (id),
        CONSTRAINT "FK_media_genres_media_media_id" FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE TABLE media_producers (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        media_id uuid NOT NULL,
        producer character varying(50) NOT NULL,
        CONSTRAINT "PK_media_producers" PRIMARY KEY (id),
        CONSTRAINT "FK_media_producers_media_media_id" FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE TABLE media_writers (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        media_id uuid NOT NULL,
        writer character varying(50) NOT NULL,
        CONSTRAINT "PK_media_writers" PRIMARY KEY (id),
        CONSTRAINT "FK_media_writers_media_media_id" FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_media_cast_media_id_cast_member" ON media_cast (media_id, cast_member);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_media_directors_media_id_director" ON media_directors (media_id, director);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_media_genres_media_id_genre" ON media_genres (media_id, genre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_media_producers_media_id_producer" ON media_producers (media_id, producer);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_media_writers_media_id_writer" ON media_writers (media_id, writer);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_users_user_name" ON users (user_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013215024_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251013215024_InitialCreate', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017193532_Thumbnail') THEN
    ALTER TABLE media ADD thumbnail double precision;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017193532_Thumbnail') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251017193532_Thumbnail', '9.0.9');
    END IF;
END $EF$;
COMMIT;

