// <auto-generated />
using System;
using MediaBrowser;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaBrowser.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    partial class MediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MediaBrowser.Media.Cast.CastEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CastMember")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("cast_member");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "CastMember")
                        .IsUnique();

                    b.ToTable("media_cast", (string)null);
                });

            modelBuilder.Entity("MediaBrowser.Media.Directors.DirectorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("director");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Director")
                        .IsUnique();

                    b.ToTable("media_directors", (string)null);
                });

            modelBuilder.Entity("MediaBrowser.Media.Genres.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("genre");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Genre")
                        .IsUnique();

                    b.ToTable("media_genres", (string)null);
                });

            modelBuilder.Entity("MediaBrowser.Media.MediaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<string>("CtimeMs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ctime_ms");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL")
                        .HasColumnName("duration");

                    b.Property<string>("Ffprobe")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ffprobe");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("md5");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mime");

                    b.Property<string>("MtimeMs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mtime_ms");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("original_title");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("Published")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("published");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_on");

                    b.Property<int?>("UserStarRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_star_rating");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("MediaBrowser.Media.Producers.ProducerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("producer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Producer")
                        .IsUnique();

                    b.ToTable("media_producers", (string)null);
                });

            modelBuilder.Entity("MediaBrowser.Media.Writers.WriterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("writer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Writer")
                        .IsUnique();

                    b.ToTable("media_writers", (string)null);
                });

            modelBuilder.Entity("MediaBrowser.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MediaBrowser.Media.Cast.CastEntity", b =>
                {
                    b.HasOne("MediaBrowser.Media.MediaEntity", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaBrowser.Media.Directors.DirectorEntity", b =>
                {
                    b.HasOne("MediaBrowser.Media.MediaEntity", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaBrowser.Media.Genres.GenreEntity", b =>
                {
                    b.HasOne("MediaBrowser.Media.MediaEntity", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaBrowser.Media.Producers.ProducerEntity", b =>
                {
                    b.HasOne("MediaBrowser.Media.MediaEntity", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaBrowser.Media.Writers.WriterEntity", b =>
                {
                    b.HasOne("MediaBrowser.Media.MediaEntity", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
