// <auto-generated />
using System;
using MediaBrowser;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaBrowser.Migrations
{
    [DbContext(typeof(MediaSqliteDbContext))]
    partial class MediaSqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MediaBrowser.Media.Cast.CastEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<Guid>("MediaId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id")
                        .HasAnnotation("Relational:JsonPropertyName", "mediaId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("cast_member")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Name")
                        .IsUnique();

                    b.ToTable("media_cast");

                    b.HasAnnotation("Relational:JsonPropertyName", "cast");
                });

            modelBuilder.Entity("MediaBrowser.Media.Directors.DirectorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<Guid>("MediaId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id")
                        .HasAnnotation("Relational:JsonPropertyName", "mediaId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("director")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Name")
                        .IsUnique();

                    b.ToTable("media_directors");

                    b.HasAnnotation("Relational:JsonPropertyName", "directors");
                });

            modelBuilder.Entity("MediaBrowser.Media.Genres.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<Guid>("MediaId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id")
                        .HasAnnotation("Relational:JsonPropertyName", "mediaId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("genre")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Name")
                        .IsUnique();

                    b.ToTable("media_genres");

                    b.HasAnnotation("Relational:JsonPropertyName", "genres");
                });

            modelBuilder.Entity("MediaBrowser.Media.MediaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on")
                        .HasAnnotation("Relational:JsonPropertyName", "createdOn");

                    b.Property<long>("CtimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ctime_ms")
                        .HasAnnotation("Relational:JsonPropertyName", "ctimeMs");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL")
                        .HasColumnName("duration")
                        .HasAnnotation("Relational:JsonPropertyName", "duration");

                    b.Property<string>("Ffprobe")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ffprobe")
                        .HasAnnotation("Relational:JsonPropertyName", "ffprobe");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height")
                        .HasAnnotation("Relational:JsonPropertyName", "height");

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("md5")
                        .HasAnnotation("Relational:JsonPropertyName", "md5");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("mime")
                        .HasAnnotation("Relational:JsonPropertyName", "mime");

                    b.Property<long>("MtimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mtime_ms")
                        .HasAnnotation("Relational:JsonPropertyName", "mtimeMs");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_title")
                        .HasAnnotation("Relational:JsonPropertyName", "originalTitle");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("path")
                        .HasAnnotation("Relational:JsonPropertyName", "path");

                    b.Property<string>("Published")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("published")
                        .HasAnnotation("Relational:JsonPropertyName", "published");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size")
                        .HasAnnotation("Relational:JsonPropertyName", "size");

                    b.Property<double?>("Thumbnail")
                        .HasColumnType("REAL")
                        .HasColumnName("thumbnail")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_on")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedOn");

                    b.Property<int?>("UserStarRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_star_rating")
                        .HasAnnotation("Relational:JsonPropertyName", "userStarRating");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width")
                        .HasAnnotation("Relational:JsonPropertyName", "width");

                    b.HasKey("Id");

                    b.ToTable("media");
                });

            modelBuilder.Entity("MediaBrowser.Media.Producers.ProducerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<Guid>("MediaId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id")
                        .HasAnnotation("Relational:JsonPropertyName", "mediaId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("producer")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Name")
                        .IsUnique();

                    b.ToTable("media_producers");

                    b.HasAnnotation("Relational:JsonPropertyName", "producers");
                });

            modelBuilder.Entity("MediaBrowser.Media.Writers.WriterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<Guid>("MediaId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id")
                        .HasAnnotation("Relational:JsonPropertyName", "mediaId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("writer")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Name")
                        .IsUnique();

                    b.ToTable("media_writers");

                    b.HasAnnotation("Relational:JsonPropertyName", "writers");
                });

            modelBuilder.Entity("MediaBrowser.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("MediaBrowser.Media.Cast.CastEntity", b =>
                {
                    b.HasOne("MediaBrowser.Media.MediaEntity", "Media")
                        .WithMany("Cast")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaBrowser.Media.Directors.DirectorEntity", b =>
                {
                    b.HasOne("MediaBrowser.Media.MediaEntity", "Media")
                        .WithMany("Directors")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaBrowser.Media.Genres.GenreEntity", b =>
                {
                    b.HasOne("MediaBrowser.Media.MediaEntity", "Media")
                        .WithMany("Genres")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaBrowser.Media.Producers.ProducerEntity", b =>
                {
                    b.HasOne("MediaBrowser.Media.MediaEntity", "Media")
                        .WithMany("Producers")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaBrowser.Media.Writers.WriterEntity", b =>
                {
                    b.HasOne("MediaBrowser.Media.MediaEntity", "Media")
                        .WithMany("Writers")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaBrowser.Media.MediaEntity", b =>
                {
                    b.Navigation("Cast");

                    b.Navigation("Directors");

                    b.Navigation("Genres");

                    b.Navigation("Producers");

                    b.Navigation("Writers");
                });
#pragma warning restore 612, 618
        }
    }
}
