global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IdentityModel.Tokens.Jwt;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using System.Text;
global using System.Text.Json.Nodes;
global using System.Text.RegularExpressions;
global using System.Web;
global using MediaBrowser.Media.Cast;
global using MediaBrowser.Media.Directors;
global using MediaBrowser.Media.Genres;
global using MediaBrowser.Media.Import;
global using MediaBrowser.Media.Producers;
global using MediaBrowser.Media.Writers;
global using MediaBrowser.TestFiles;
global using MediaBrowser.Users;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Data.SqlClient;
global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using MySqlConnector;
global using Npgsql;
global using NUnit.Framework;
global using Shouldly;
global using HeaderNames = Microsoft.Net.Http.Headers.HeaderNames;
global using RangeHeaderValue = System.Net.Http.Headers.RangeHeaderValue;
global using Stream = System.IO.Stream;